- name: Create direcotry .ssh for {{ admin_user }}
  file: path=/home/{{ admin_user }}/.ssh state=directory owner={{ admin_user }} group={{ admin_user }} mode=0700

- name: Create authorized_keys for {{ admin_user }}
  copy:
    src: "keys/{{ admin_user }}.pub"
    dest: "/home/{{ admin_user }}/.ssh/authorized_keys"
    force: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: 0600