- name: Make sure we have a 'sudo' group
  group: name=sudo state=present

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile: 
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: Add user with administrative privileges
  user: name={{ admin_user }} shell=/bin/bash groups=sudo append=yes