---
- name: Create a strong Diffie-Hellman group
  command: openssl dhparam -out {{ dhparam_pem }} 2048 creates={{ dhparam_pem }}

- name: Create self-signed SSL certificate
  command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=RU/ST=Primorsy kray/L=Vladivostok/O=Appreactor/CN={{ www_server_name }}" -keyout {{ ssl_certificate_key }} -out {{ ssl_certificate }} creates={{ ssl_certificate }}