# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "192.168.34.10"

  config.vm.synced_folder "../www/", "/var/www/devbox",
        owner: "ubuntu",
        group: "www-data",
        mount_options: ["dmode=775,fmode=764"]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.provision :shell, path: "bootstrap.sh"
end