# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bskton/web"

  config.vm.network "private_network", ip: "192.168.34.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.name = "webdev"
    vb.memory = "512"
  end

  config.vm.provision :shell, path: "bootstrap.sh"
end