---
- name: Install php-fpm
  apt: name=php-fpm state=latest
  notify: restart php-fpm

- name: Copy php-fpm configuration for host
  copy: src=php.ini dest=/etc/php/7.0/fpm/ owner=root group=root mode=0644
  notify: restart php-fpm

- name: Install php-mbstring
  apt: name=php-mbstring state=latest
  notify: restart php-fpm

- name: Install php-zip
  apt: name=php-zip state=latest
  notify: restart php-fpm

- name: Install php-xml
  apt: name=php-xml state=latest
  notify: restart php-fpm