---
- name: Install nginx
  apt: name=nginx state=latest
  notify: restart nginx

- name: Create www directory
  file:
    path: "{{ site_root }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: 0755

- name: Copy nginx configuration for host
  template:
    src: default.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart nginx