# Плэйбук для первоначальной настройки сервера.
# Создает создает пользователя с административными правами и
# ключи доступа для него.

---
- hosts: devbox
  remote_user: "{{ admin_user }}"
  become: yes
  become_user: root
  
  roles:
    - iptables
    - ssh
    - user
    - ssl
    - nginx
    - php
    - composer
    - redis
    - phpunit
    - xdebug
    - phpdoc
    - mongodb