# Плэйбук для первоначальной настройки сервера.
# Создает создает пользователя с административными правами и
# ключи доступа для него.

---
- hosts: webdev
  remote_user: "{{ admin_user }}"
  become: yes
  become_user: root
  
  roles:
    - ssh
    - iptables
    - php
    - ssl
    - nginx
    - composer